package com.dynablox.launcher.ui

import android.opengl.GLSurfaceView
import android.widget.HorizontalScrollView
import android.widget.LinearLayout
import android.widget.TextView
import com.dynablox.launcher.R
import com.dynablox.launcher.core.commands.CommandFeedback
import com.dynablox.launcher.core.util.Fmt
import com.dynablox.launcher.design.widgets.PhysicalButton
import com.dynablox.launcher.shader.ShaderLabRenderer
import com.dynablox.launcher.shader.ShaderPresets

/**
 * Shader Lab.
 *
 * A real OpenGL ES 2.0 pipeline: the fragment sources in [ShaderPresets] are compiled on the device
 * at runtime, the driver's own info log is shown when compilation fails, and the render rate is
 * measured from the GL thread. Everything on screen is generated by the GPU over a procedural test
 * scene — there is no screenshot, no video and no pre-rendered image anywhere in this feature.
 */
class ShaderLabActivity : DbxActivity() {

    override val titleRes: Int = R.string.title_shader_lab
    override val subtitleRes: Int = R.string.shader_subtitle
    override val headerIconRes: Int = R.drawable.ic_shader
    override val scrollsContent: Boolean = false

    private val renderer = ShaderLabRenderer()
    private var glView: GLSurfaceView? = null
    private var fpsView: TextView? = null
    private var statusView: TextView? = null
    private var currentPreset = ShaderPresets.ALL.first()
    private var lastFps = 0f

    override fun buildContent(root: LinearLayout) {
        currentPreset = ShaderPresets.byId(settings.shaderPreset)
        applyPresetToRenderer(currentPreset)
        buildPreview()
        buildPresetPicker()
        buildParams()
        buildActions()
    }

    private fun applyPresetToRenderer(preset: com.dynablox.launcher.shader.ShaderPreset) {
        renderer.preset = preset
        preset.params.forEach { param ->
            val value = settings.shaderParam(param.id, param.default)
            when (param.id) {
                "amount" -> renderer.amount = value
                "grain" -> renderer.paramB = value
                "speed" -> renderer.paramC = value
                else -> renderer.amount = value
            }
        }
    }

    private fun buildPreview() {
        section(R.string.shader_section_preview, R.string.shader_section_preview_desc)
        card {
            val gl = GLSurfaceView(this@ShaderLabActivity).apply {
                setEGLContextClientVersion(2)
                setRenderer(renderer)
                renderMode = GLSurfaceView.RENDERMODE_CONTINUOUSLY
            }
            glView = gl
            renderer.onRenderFps = { fps ->
                lastFps = fps
                runOnUiThread { fpsView?.text = Fmt.number(fps, 1) }
            }
            renderer.onPresetReady = { id ->
                runOnUiThread {
                    statusView?.text = getString(R.string.shader_status_compiled, id)
                    statusView?.setTextColor(tokens.success)
                }
            }
            renderer.onCompileError = { log ->
                runOnUiThread {
                    statusView?.text = getString(R.string.shader_status_failed, log.take(160))
                    statusView?.setTextColor(tokens.danger)
                }
            }
            addView(
                gl,
                LinearLayout.LayoutParams(
                    LinearLayout.LayoutParams.MATCH_PARENT, dp(230f).toInt(),
                ),
            )
            divider()
            fpsView = textRow(R.string.shader_render_fps, if (lastFps > 0f) Fmt.number(lastFps, 1) else "--")
            statusView = textRow(R.string.shader_status, getString(R.string.shader_status_idle))
            textRow(R.string.shader_renderer, rendererInfo())
        }
    }

    private fun rendererInfo(): String =
        getString(R.string.shader_renderer_value, renderer.glVersion ?: getString(R.string.shader_status_idle))

    private fun buildPresetPicker() {
        section(R.string.shader_section_presets, R.string.shader_section_presets_desc)
        card {
            val scroll = HorizontalScrollView(this@ShaderLabActivity).apply { isHorizontalScrollBarEnabled = false }
            val row = LinearLayout(this@ShaderLabActivity).apply { orientation = LinearLayout.HORIZONTAL }
            ShaderPresets.ALL.forEach { preset ->
                val button = PhysicalButton(this@ShaderLabActivity).apply {
                    label = getString(preset.nameRes)
                    shape = PhysicalButton.Shape.CAPSULE
                    isActivated = preset.id == currentPreset.id
                    setOnClickListener { selectPreset(preset) }
                }
                row.addView(
                    button,
                    LinearLayout.LayoutParams(
                        LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT,
                    ).apply { marginEnd = dp(8f).toInt() },
                )
            }
            scroll.addView(row)
            addView(
                scroll,
                LinearLayout.LayoutParams(
                    LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT,
                ),
            )
            paragraph(R.string.shader_presets_desc)
        }
    }

    private fun selectPreset(preset: com.dynablox.launcher.shader.ShaderPreset) {
        currentPreset = preset
        settings.shaderPreset = preset.id
        applyPresetToRenderer(preset)
        statusView?.text = getString(R.string.shader_status_compiling, preset.id)
        statusView?.setTextColor(tokens.textSecondary)
        refreshContent()
    }

    private fun buildParams() {
        section(R.string.shader_section_params, R.string.shader_section_params_desc)
        card {
            currentPreset.params.forEach { param ->
                val value = settings.shaderParam(param.id, param.default)
                faderRow(
                    labelRes = param.labelRes,
                    min = 0f, max = 100f,
                    value = value * 100f,
                    unit = "%",
                ) { raw ->
                    val next = (raw / 100f).coerceIn(0f, 1f)
                    settings.setShaderParam(param.id, next)
                    when (param.id) {
                        "amount" -> renderer.amount = next
                        "grain" -> renderer.paramB = next
                        "speed" -> renderer.paramC = next
                        else -> renderer.amount = next
                    }
                }
            }
            faderRow(
                labelRes = R.string.shader_time_scale,
                min = 0f, max = 300f,
                value = renderer.timeScale * 100f,
                unit = "%",
            ) { renderer.timeScale = (it / 100f).coerceIn(0f, 3f) }
        }
    }

    private fun buildActions() {
        section(R.string.shader_section_actions)
        card {
            buttonRow(
                if (renderer.paused) R.string.shader_resume else R.string.shader_pause,
                if (renderer.paused) R.drawable.ic_play else R.drawable.ic_pause,
            ) {
                renderer.paused = !renderer.paused
                if (renderer.paused) glView?.renderMode = GLSurfaceView.RENDERMODE_WHEN_DIRTY
                else glView?.renderMode = GLSurfaceView.RENDERMODE_CONTINUOUSLY
                refreshContent()
            }
            buttonRow(R.string.shader_reset_params, R.drawable.ic_refresh) {
                currentPreset.params.forEach { settings.clearShaderParam(it.id) }
                applyPresetToRenderer(currentPreset)
                show(getString(R.string.shader_params_reset), CommandFeedback.Kind.SUCCESS)
                refreshContent()
            }
            buttonRow(
                R.string.shader_open_fx,
                R.drawable.ic_eye,
                descriptionRes = R.string.shader_open_fx_desc,
            ) {
                val running = container.overlays.toggleFx()
                show(
                    getString(if (running) R.string.settings_fx_on else R.string.settings_fx_off),
                    CommandFeedback.Kind.INFO,
                )
            }
            paragraph(R.string.shader_honest_scope)
        }
    }

    override fun onResume() {
        super.onResume()
        glView?.onResume()
    }

    override fun onPause() {
        glView?.onPause()
        super.onPause()
    }
}
